New getting started guide
NomicFoundation/hardhat pull request #2820
Opened 2022-06-11 19:23 UTC by alcuadrado

The new getting started guide, using the new sample projects.

Can you review it, @feuGeneA?

2022-06-13 20:20 UTC, feuGeneA requested changes

2022-06-13 20:20 UTC, feuGeneA commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
> +You can run your tests with `npx hardhat test`
```suggestion
You can run your tests with `npx hardhat test`:
```

2022-06-13 20:20 UTC, feuGeneA commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
> +Inside `scripts/` you will find a file with the following code:
```suggestion
Inside the `scripts/` folder you will find a file with the following code:
```

2022-06-13 20:20 UTC, feuGeneA commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
> +You can run it using `hardhat run`
```suggestion
You can run it using `hardhat run`:
```

2022-06-13 20:20 UTC, feuGeneA commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
> +$ npx hardhat run scripts/deploy.ts
```suggestion
$ npx hardhat run scripts/deploy.js
```

2022-06-13 20:20 UTC, feuGeneA commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
>  If you want to connect Hardhat to this node to, for example, run a deployment script against it, you simply need to run it using `--network localhost`.
```suggestion
If you want to connect Hardhat to this node, for example to run a deployment script against it, you simply need to run it using `--network localhost`.
```

2022-06-13 20:20 UTC, feuGeneA commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
> +Congrats! You have created a project, compiled a smart contract, tested, and deployed it.
```suggestion
Congrats! You have created a project and compiled, tested and deployed a smart contract.
```

2022-06-13 20:20 UTC, feuGeneA commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
> +::::tabsgroup{options="npm 7+,npm 6,yarn"}
Is there a reason to have a separate tab for `npm 7+` and `npm 6`? They both have the same content. (Right?)

2022-06-14 18:47 UTC, alcuadrado commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
> +:::tab{value="npm 7+"}
Thanks. I figured out what it is. I know how to workaround it.

2022-06-14 18:51 UTC, alcuadrado commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
> +This is the list of built-in tasks, plus others that come from the recommended plugins you just installed. This is your starting point to find out what tasks are available to run.
Right

2022-06-14 18:52 UTC, alcuadrado commented on docs/src/content/hardhat-runner/docs/getting-started/index.md
> +If you take a look at `test/`, you should be able to a test file:
The reason for that is that we can't show a different file name for TS/JS.

2022-06-14 20:29 UTC, merged