Issue #2170: New check for getContractAt()
NomicFoundation/hardhat pull request #2916
Opened 2022-07-09 17:05 UTC by SfyMantissa

- [x] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.

---

New feature. Was previously discussed in [Issue #2170](https://github.com/NomicFoundation/hardhat/issues/2170).
Adds a check for input address to `getContractAt()` — now it MUST have code (be a contract), otherwise function throws.

What was done:

- [x] Changes to the module itself
- [x] Test update
- [x] README update 

All tests run fine:

![image](https://user-images.githubusercontent.com/38407640/178115745-d8d8fc71-2484-4a43-8ba8-0e1c3a306597.png)

**Let me know if anything else is needed for submission :)**

2022-07-11 19:34 UTC, feuGeneA requested changes
Thank you for this!

2022-07-11 19:34 UTC, feuGeneA commented on packages/hardhat-ethers/README.md
> +If a non-contract address is provided to `getContractAt`, an error will be thrown.
```suggestion
If the address provided to `getContractAt` is not the address of a contract account, an error will be thrown.
```

2022-07-11 19:34 UTC, feuGeneA commented on packages/hardhat-ethers/src/internal/helpers.ts
> +      `${address} is a non-contract address.`
```suggestion
      `${address} is not a contract account.`
```

2022-07-11 19:34 UTC, feuGeneA commented on packages/hardhat-ethers/test/index.ts
> +              `${address} is a non-contract address.`
```suggestion
              `${address} is not a contract account.`
```

2022-07-13 09:30 UTC, SfyMantissa commented
Hi!
I accepted the proposed changes to the description strings.
Is there anything else needed to accept this PR?

2022-08-02 17:48 UTC, SfyMantissa commented
Hi!
Sorry for bothering, is there anything else that needs to be polished/added?

2022-08-04 22:09 UTC, feuGeneA approved these changes

2022-08-04 22:10 UTC, merged