hardhat-verify: fix list supported networks issue
NomicFoundation/hardhat pull request #4030
Opened 2023-06-14 13:27 UTC by clauBv23

- [x] Because this PR includes a **bug fix**, relevant tests have been included.
- [ ] Because this PR includes a **new feature**, the change was previously discussed on an Issue or with someone from the team.
- [ ] I didn't do anything of this.

---

Fixes: #4023 

A new task was added for listing the supported networks and it was used to list them without having to pass an address as a parameter.

2023-06-14 16:00 UTC, schaable requested changes
Hey, @clauBv23! Thanks for the pull request. Please take a look at my comments above and let me know if you have any questions or need further clarification. You can also fix the typo on this same PR.

2023-06-14 16:51 UTC, clauBv23 commented on packages/hardhat-verify/test/unit/index.ts
> +  describe("verify:get-supported-networks-list", () => {
Perfect, I just removed the not needed params to check it works as expected without them, not sure if something else should be done to tests it

2023-06-14 20:17 UTC, schaable approved these changes
Looks good!

2023-06-16 07:14 UTC, fvictorio approved these changes

2023-06-16 07:14 UTC, merged

2023-06-16 07:14 UTC, fvictorio commented
Thanks!