Add basic Sourcify verification
NomicFoundation/hardhat pull request #4317
Opened 2023-08-22 13:36 UTC by marcocastignoli

Add the basic functions, tasks and tests to provide Sourcify verification

2023-08-26 13:40 UTC, schaable requested changes
Hey @marcocastignoli, thanks for sending in the PR! I've dropped a few comments for you. If you want more info or have any questions, feel free to ask.

2023-08-26 13:40 UTC, schaable commented on packages/hardhat-verify/src/internal/sourcify.ts
> +const VERIFICATION_STATUS_POLLING_TIME = 3000;
```suggestion
```

2023-08-26 13:40 UTC, schaable commented on packages/hardhat-verify/src/internal/tasks/sourcify.ts
> +}
The verification interface is Sourcify. Don't redefine it, you can do:
```suggestion

interface AttemptVerificationArgs {
  address: string;
  verificationInterface: Sourcify;
  contractFQN: string;
}
```

2023-08-26 13:40 UTC, schaable commented on packages/hardhat-verify/test/integration/index.ts
> +    it("should verify a contract on Sourcify", async function () {
This is ok, but I'd add some tests for the error scenarios as well.

2023-08-28 14:26 UTC, schaable commented on packages/hardhat-verify/src/internal/tasks/sourcify.ts
> +      if (!network.config.chainId) {
Sorry for leaving a comment after the initial review. I wasn't sure about this so I wanted to confirm it first. `network.config.chainId` is not reliable to get the chain id, as this value is obtained from the user config. You need to use the `eth_chainId` RPC method, like [here](https://github.com/NomicFoundation/hardhat/blob/1c472a9e6dce792f7a9a94da4db8f3db282efedf/packages/hardhat-verify/src/internal/etherscan.ts#L49).

2023-08-29 08:51 UTC, marcocastignoli commented on packages/hardhat-verify/src/internal/sourcify.ts
> +  // https://docs.sourcify.dev/docs/api/server/check-all-by-addresses/
Old docs url, the new one is: https://sourcify.dev/server/api-docs/#/Repository/get_check_all_by_addresses

2023-08-29 08:53 UTC, marcocastignoli commented on packages/hardhat-verify/src/internal/sourcify.ts
> +  // https://docs.sourcify.dev/docs/api/server/verify/
here again: https://sourcify.dev/server/api-docs/#/Stateless%20Verification/post_verify

2023-08-29 08:57 UTC, marcocastignoli commented on packages/hardhat-verify/src/internal/sourcify.ts
> +      const responseText = await response.body.text();
yes but the message key is not always consistent, so I would print the JSON.stringify of the error

2023-08-29 11:42 UTC, marcocastignoli commented on packages/hardhat-verify/src/internal/sourcify.ts
> +      return contract.status;
we actually need the status string so we can process the url to the contract on Sourcify

2023-09-18 15:33 UTC, merged