feat: add `eth_getBlockByNumber` support
NomicFoundation/hardhat pull request #4627
Opened 2023-11-28 17:22 UTC by agostbiro

Adds `eth_getBlockByNumber` support to the EDR provider, matching the Hardhat implementation. 

Hardhat integration tests are passing up to the point where they need `eth_sendTransaction`.

2023-11-28 18:06 UTC, Wodann requested changes
Mostly LGTM. A couple of comments for clarification

2023-11-29 10:45 UTC, agostbiro commented on crates/edr_evm/src/block/remote.rs
> +        let size = block
Doesn't mandate it as far as I can tell. I changed the size type from `U256` to `u64` on the remote type: [c40e020](https://github.com/NomicFoundation/hardhat/pull/4627/commits/c40e0206e4424773d7ef59a8931f093e84cc95ad)

2023-11-29 10:45 UTC, agostbiro commented on crates/edr_evm/src/block/remote.rs
> +    size: u64,
Done in [c40e020](https://github.com/NomicFoundation/hardhat/pull/4627/commits/c40e0206e4424773d7ef59a8931f093e84cc95ad)

2023-11-29 10:45 UTC, agostbiro commented on crates/edr_evm/src/block.rs
> +    fn size(&self) -> u64;
Good idea, done in [c40e020](https://github.com/NomicFoundation/hardhat/pull/4627/commits/c40e0206e4424773d7ef59a8931f093e84cc95ad)

2023-11-29 11:17 UTC, Wodann approved these changes

2023-11-29 11:17 UTC, merged