fix: handle unknown selector error
NomicFoundation/hardhat pull request #4811
Opened 2024-02-01 20:09 UTC by Wodann

Fixes https://github.com/NomicFoundation/edr/issues/281

2024-02-01 20:09 UTC, Wodann commented on crates/edr_provider/src/error.rs
> +            ),
@agostbiro you're more familiar with this code. Can we logically rule out that none of the other error variants can occur?

2024-02-02 09:16 UTC, agostbiro requested changes
Thanks for the quick fixes @Wodann ! I left some comments

2024-02-02 15:17 UTC, Wodann commented on crates/edr_provider/src/error.rs
> +            | alloy_sol_types::Error::UnknownSelector { .. } => {
I tested the test with the issue you mentioned and it did, yes.

I can double check

2024-02-02 18:49 UTC, Wodann commented on crates/edr_provider/src/error.rs
> +            | alloy_sol_types::Error::UnknownSelector { .. } => {
You're right. It does not fix [#283](https://github.com/NomicFoundation/edr/issues/283). Aplogies

2024-02-02 19:02 UTC, Wodann commented on crates/edr_provider/src/error.rs
> +            ),
Addressed in https://github.com/NomicFoundation/hardhat/pull/4811/commits/3e86c0d9be3bcf6c1ba195134449e6c39f01e3b2

2024-02-05 09:34 UTC, agostbiro approved these changes

2024-02-05 09:35 UTC, merged