build: remove support for i686 & arm windows builds
NomicFoundation/hardhat pull request #5108
Opened 2024-04-11 13:54 UTC by Wodann

2024-04-11 16:30 UTC, agostbiro requested changes
Thanks, could you also remove all references to `i686-pc-windows-msvc` and `aarch64-pc-windows-msvc` from `.github/workflows/edr-npm-release.yml`?

2024-04-12 07:57 UTC, fvictorio approved these changes

2024-04-12 09:29 UTC, Wodann commented
> Thanks, could you also remove all references to `i686-pc-windows-msvc` and `aarch64-pc-windows-msvc` from `.github/workflows/edr-npm-release.yml`?

Thanks. Good call!

Addressed in https://github.com/NomicFoundation/hardhat/pull/5108/commits/f2facd3f5ff96b15a437392746a6a9410f3fb7bc

2024-04-12 09:45 UTC, agostbiro approved these changes
Thanks, LGTM assuming CI passes.

2024-04-12 14:51 UTC, merged