Make options optional
NomicFoundation/hardhat pull request #5499
Opened 2024-07-09 16:35 UTC by schaable

Merge after https://github.com/NomicFoundation/hardhat/pull/5495
Closes https://github.com/NomicFoundation/hardhat/issues/5419

2024-07-09 21:59 UTC, alcuadrado commented on v-next/core/src/internal/tasks/resolved-task.ts
> +        taskArguments[option.name] = option.defaultValue;
I wouldn't modify this input here.

2024-07-09 22:02 UTC, alcuadrado requested changes
I just left two small comments.

Unfortunately, I think all your open PRs need to be rebased because of the new assertion-related eslint rules.

2024-07-10 13:30 UTC, schaable commented on v-next/core/src/internal/tasks/resolved-task.ts
> +        taskArguments[option.name] = option.defaultValue;
Will be addressed in a follow-up PR.

2024-07-10 13:31 UTC, alcuadrado approved these changes

2024-07-10 13:32 UTC, merged