Basic debug logging
NomicFoundation/hardhat pull request #5541
Opened 2024-07-23 05:31 UTC by zoeyTM

- added basic debug logging throughout the main CLI function
- added a `withDebugLogs` decorator to core to easily enable debug logging to any class method
  - added this decorator to some class methods that I thought would be helpful, but it can always be added to others in the future as well

fixes #5363

2024-07-23 08:10 UTC, ChristopherDedominici approved these changes
LGTM (I saw the comment about the issue with tsx)

I love the idea of the decorator! 
One suggestion:  what about a class level decorator that will automatically log for all the methods of the class? So you only have to add it at the beginning instead of every method

2024-07-28 17:06 UTC, alcuadrado commented
I've been testing this, and I think this is too verbose to be useful. I believe the decorator approach will lead to printing too much data, so I think it's better to remove it and manually log what we find useful.

For example, I think logging these things is useful, but they could be much more succinct:
* running hooks in the hook manager, which one is run and how.
* The HRE being created, maybe not even with the config. But knowing that we are creating an HRE can be helpful to debug potential errors (e.g. creating multiple of them by accident)
* Running a task, but maybe not creating/inserting/fetching them (as that's really verbose)

2024-07-28 17:07 UTC, alcuadrado commented on v-next/hardhat/src/internal/cli/main.ts
> +    log("Parsing builtin global options");
I think printing just the results would probably be enough in most cases, and make the output less verbose/more helpful.

2024-07-28 17:08 UTC, alcuadrado commented on v-next/hardhat/src/internal/cli/main.ts
> +    log("Parsing builtin global options");
I mean in general. I noticed a pattern of "doing this", "this is its result", which I do a ton for manual debugging, but can be too verbose.

2024-07-28 17:08 UTC, alcuadrado requested changes
Just left a few comments

2024-08-01 20:39 UTC, alcuadrado approved these changes

2024-08-07 10:30 UTC, merged